from registry.access.redhat.com/rhel9/postgresql-16

ENV PGDATA=/var/lib/pgsql/pgdata 
ENV POSTGRESQL_USER=postgres 
ENV POSTGRESQL_PASSWORD=postgres 
ENV POSTGRESQL_DATABASE=postgres

COPY dumpdb-init.sql /opt/app-root/src/

RUN initdb --auth=trust --auth-host=trust --auth-local=trust && \
    pg_ctl start -o "-h ''" && \
    psql -c "ALTER ROLE postgres WITH ENCRYPTED PASSWORD ''" && \
    psql -f /opt/app-root/src/dumpdb-init.sql && \
    pg_ctl stop && \
    sed -ie 's;host  *all  *all  *::1/128.*;host    all             all             0.0.0.0/0               trust;g' /var/lib/pgsql/pgdata/pg_hba.conf  && \
    echo "listen_addresses = '*'" >> /var/lib/pgsql/pgdata/postgresql.conf

WORKDIR /var/lib/pgsql

