from registry.access.redhat.com/ubi10/ubi:10.0-1754586730

ENV PGDATA=/var/lib/pgsql/pgdata 
ENV POSTGRESQL_USER=postgres 
ENV POSTGRESQL_PASSWORD=postgres 
ENV POSTGRESQL_DATABASE=postgres
ENV PATH="$PATH:/usr/pgsql-17/bin"

RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm && \
    dnf install -y inotify-tools && \
    dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-10-x86_64/pgdg-redhat-repo-latest.noarch.rpm && \
    dnf install -y postgresql17-plpython3 && \
    dnf install -y postgresql17-server && \
    dnf install -y python3-yaml

COPY dumpdb-init.sql /var/lib/pgsql/

USER postgres
WORKDIR /var/lib/pgsql

RUN initdb --auth=trust --auth-host=trust --auth-local=trust && \
    pg_ctl start -o "-h ''" && \
    psql -c "ALTER ROLE postgres WITH ENCRYPTED PASSWORD ''" && \
    psql -f dumpdb-init.sql && \
    pg_ctl stop && \
    sed -ie 's;host  *all  *all  *::1/128.*;host    all             all             0.0.0.0/0               trust;g' /var/lib/pgsql/pgdata/pg_hba.conf  && \
    echo "listen_addresses = '*'" >> /var/lib/pgsql/pgdata/postgresql.conf && \
    sed -ie 's/^logging_collector/#logging_collector/g' /var/lib/pgsql/pgdata/postgresql.conf && \
    mkdir /tmp/kcdump && \
    chmod 777 /tmp/kcdump

ENV KCDUMP_DIR=/tmp/kcdump

ENTRYPOINT postgres





