FROM registry.access.redhat.com/hi/go:latest AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
COPY pkg/ pkg/
COPY cmd/main.go cmd/main.go

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o kcdump cmd/main.go

FROM docker.io/svenstaro/miniserve:latest as miniserve

FROM registry.access.redhat.com/hi/python:3.14-builder

USER 0

ENV PGDATA=/var/lib/pgsql/pgdata 
ENV POSTGRESQL_USER=postgres 
ENV POSTGRESQL_PASSWORD=postgres 
ENV POSTGRESQL_DATABASE=postgres

RUN dnf install -y postgresql postgresql-devel postgresql-plpython3 python3-yaml && \
    mkdir -p /var/run/postgresql && \
    groupmod -g 999 postgres && \
    usermod -u 999 -g 999 postgres && \
    chown -R 999:999 /usr/lib64/pgsql && \
    chown -R 999:999 /var/run/postgresql && \
    chown -R 999:999 /var/lib/pgsql && \
    mkdir /tmp/kcdump && \
    chmod -R 777 /tmp/kcdump        

COPY --from=builder /workspace/kcdump /bin/
COPY --from=miniserve /app/miniserve /bin/
COPY dumpdb/dumpdb-init.sql /var/lib/pgsql/
COPY dumpdb/entrypoint.py /var/lib/pgsql/

USER postgres
WORKDIR /var/lib/pgsql

RUN initdb --auth=trust --auth-host=trust --auth-local=trust && \
    pg_ctl start -o "-h ''" && \
    psql -c "ALTER ROLE postgres WITH ENCRYPTED PASSWORD ''" && \
    psql -f dumpdb-init.sql && \
    pg_ctl stop && \
    sed -ie 's;host  *all  *all  *::1/128.*;host    all             all             0.0.0.0/0               trust;g' /var/lib/pgsql/pgdata/pg_hba.conf  && \
    echo "host    all             all             ::1/128                 trust" >> /var/lib/pgsql/pgdata/pg_hba.conf  && \
    echo "listen_addresses = '*'" >> /var/lib/pgsql/pgdata/postgresql.conf && \
    sed -ie 's/^logging_collector/#logging_collector/g' /var/lib/pgsql/pgdata/postgresql.conf 

USER 0
RUN find /usr/bin /usr/local/bin/ /bin -type f,l | while read b; do f=`echo $b | sed -e 's;.*/;;g'`; if [[ "$f" =~ ^(bash|sh|dash|ash|zsh|csh|apt|apt-get|dpkg|apk|yum|dnf|rpm|curl|wget|nc|netcat|ncat|socat|telnet|tp|sh|scp|rsync|ping|traceroute|netstat|ss|ip|arp|nmap|ps|top|htop|uname|whoami|id|env|lsof|strace|cpdump|gdb|tar|gzip|bzip2|zip|unzip|awk|grep|find|vi|vim|nano|ed)$ ]]; then rm -f $b; fi; done && \
    rm -f /usr/bin/sed    

USER postgres
WORKDIR /var/lib/pgsql

ENV KCD_TARGETDIR=/tmp/kcdump
ENV KCD_LOGLEVEL=info
ENV DUMP_AND_LOAD=false

EXPOSE 5432 8000

ENTRYPOINT ["python3", "/var/lib/pgsql/entrypoint.py"]

LABEL name="dumpdb" \
      vendor="Red Hat Adoption LATAM" \
      version="0.1.0" \
      release="1" \
      summary="Utility to dump Kubernetes cluster information into a ephemeral PostgreSQL database" \
      description="A utility to dump Kubernetes cluster information into a ephemeral PostgreSQL database"