# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build
      run: make build
      
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: bin/kcdump
        name: Release latest
        draft: false
        prerelease: false
    - name: Build and push with Podman
      env:
        IMG: quay.io/hcreport/kcdump
      run: |-
        echo "${{ secrets.KCDUMP_DUMPDB_ROBOT_ON_QUAY }}"
        echo "${{ secrets.KCDUMP_DUMPDB_ROBOT_ON_QUAY }}" > /tmp/config.json
        export REGISTRY_AUTH_FILE=/tmp/config.json

        build_date=`date +'%Y%m%d%H%M%S'`          
        short=`echo "${{ github.sha }}" | cut -c 1-7`
        tag="${short}-${build_date}"

        podman build . -t $IMG:$tag
        podman push $IMG:$tag
        podman push $IMG:$tag $IMG:latest
